# Generated by Django 2.1.7 on 2019-03-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_auto_20190314_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sold_times',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(default='no description'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
