# Generated by Django 2.1.7 on 2019-03-24 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0007_auto_20190317_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.Products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.Users')),
            ],
            options={
                'verbose_name_plural': 'Cart',
            },
        ),
    ]
