# Generated by Django 2.1.7 on 2019-04-13 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0009_auto_20190325_0719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
