# Generated by Django 2.2.1 on 2019-06-16 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0011_users_privacy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='users',
            old_name='privacy',
            new_name='show_history',
        ),
    ]
