# Generated by Django 3.2.3 on 2021-05-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0012_auto_20190616_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='age',
            field=models.IntegerField(default=20, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='country',
            field=models.CharField(default='Egypt', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(default='Male', max_length=50, null=True),
        ),
    ]
